spring.profiles.active: development

app.name: pgmonitor-dev
app.description: a simple postgres monitoring solution (dev)

server.use-forward-headers: true
server.compression.enabled: true

management.context-path: /actuator

# LOGGING
logging.path: ./var/log
logging.file: application.log
logging.config: classpath:logback-development.xml
logging.level.org.springframework: INFO

pgmonitor.database:
  db: "postgres"
  user: "postgres"
  password: "postgres"
  host: "0.0.0.0"
  port: "5432"

pgmonitor.metrics:
  console: true
  interval-in-seconds: 10

pgmonitor.influxdb:
  enabled: true
  host: "0.0.0.0"
  port: "8086"
  database: "db_dev"
  username: "root"
  password: "root"
  skip-idle-metrics: true
  interval-in-seconds: 60
